---
# human readable model name
target_model_full: "LG G4 - all models - unified"

SRCPATH: "/home/androidsource/do-not-touch/{{ PREFIXFNAME }}"

# TWRP repo branch
git_repo_main_branch: "twrp-9.0"
los_revision: "lineage-16.0"

# specify lunch target
LUNCHTARGET: "omni_g4-eng"

git_repo_main_manifests: "https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git"

# device tree
DTURI: "https://github.com/LGgFour/android_device_lge_g4_recovery.git"
DTBRANCH: "android-9.0_enc"
DTPATH: "{{ SRCPATH }}/device/lge/g4"

# kernel
KERNPATH: "{{ SRCPATH }}/kernel/lge/g4"
KERNGIT: "https://github.com/LGgFour/kernel_lge_msm8992.git"
KERNBRANCH: "android-9.0"

