---

# human readable model name
target_model_full: "Google Pixel 8"

# extendrom stuff
use_extendrom: "true"

# do not gen a ROM checksum
skip_gen_checksum: true

# GOS_KERNEL_BRANCH:
# ROM_NAME:
# ROM_BL_TYPE:
# lunch_buildtype:

# see https://grapheneos.org/build#building
graphene_build_targets: vendorbootimage vendorkernelbootimage target-files-package otatools-package
